### PR TITLE
Added support for new offset storage formats: kafka, storm

### PR DESCRIPTION
**Pull request by hsun-cnnxty**
Hi,

We have been using this tool in production for a while and really like it.  Recently we have migrated many of applications to use Kafka internal topic instead of ZK for offset management, we also started new development of applications running on Apache Storm to consume Kafka messages.  To be able to leverage KafkaOffsetMonitor to monitor all those different type of systems,  we have enhanced the current KafkaOffsetMonitor implementation to support those two new types of offset formats.   Details can be found in the updated README.md.  As more and more Kafka applications will be migrating to use the Kafka internal topic as offset storage,  I hope these new features can benefit other users of this great tool.

Regards,

Hang

### CODE REVIEW

**Comment by Mortimerp9** [comment]
this is great, with tests too, I like it! 

could you send the contributor agreement as recommended in the readme, then I can merge this in.

Thanks for all the great work!

**Comment by hsun-cnnxty** [comment]
Great! I will find the right people in my company to sign the agreement and send it as soon as I get it.

**Comment by Mortimerp9** [comment]
this is great! Thank you!

**Comment by AndyRao** [comment]
This is great, but I think I will be more perfect if kafkaoffsetmonitor can monitor storm spout offset even if the zookeeper cluster storm uses is different from the one kafka uses, in other words, it can support multi zookeeper cluster

**Comment by Mortimerp9** [comment]
PRs are welcome, it wouldn't be too hard to add a column to the db and
multiple config inputs to monitor more than one cluster at once. Also, the
monitor process is lightweight, so you could easily start more than one on
different ports for each cluster.

**Comment by hsun-cnnxty** [comment]
Andy, if you are referring to Kafka(the source for Storm) and Storm use different ZK instances?  I think the code needs change to support that.  In my case, we have a shared ZK cluster, so it is never an issue.

**Pull request merged**
