### PR TITLE
v0.4.0: Added support for Kafka 0.9, Kerberos, SASL_PLAINTEXT + v0.4.1: Improved stability

### PR DESCRIPTION
**Pull request by rcasey212**
kafka-offset-monitor now supports Kafka brokers >= v0.9.  This includes the added support for Kerberos / SASL_PLAINTEXT!

* Upgraded Kafka bindings to 0.9.0.1 and changed kafka client to new Java-based client - supporting Kafka brokers >= v0.9 and also supporting authentication/authorization.
  * This will no longer work with versions of kafka pre-0.9.0.1, but has been tested to work on 0.9.0.1 and 0.10.
  * Re-factored usage of ZkUtils due to a significant API change from 0.8 to
0.9.
  * Added two new command-line parameters: `kafkaBrokers`, and `kafkaSecurityProtocol` -- allowing users to choose SASL_PLAINTEXT for the security protocol when using kafka as the offset storage location, but defaulting to the original PLAINTEXT protocol when no option is chosen.
  * Replaced copy-pasted wire-protocol code that retrieves metadata from the kafka brokers with an implementation that uses the kafka provided AdminClient.
  * Replaced usage of the kafka Scala client from pre-0.9 with the new kafka java-based client.
  * **NOTE:** While I have tried to make all of the necessary changes, zookeeper and storm offset storage paths have not been tested outside of the existing unit-tests.
* Refactored ZkUtilsWrapper due to underlying API change of ZkUtils.
* Changed the headings on the group include html to be more representative of the actual data.
  * Offset becomes CommittedOffset.
  * logSize becomes LogEndOffset.
* Upgraded Scala to 2.11.8
* Upgraded SBT to 13.13

### CODE REVIEW

**Comment by copoo** [comment]
@rcasey212 ,after applying your new patches for the  KafkaOffsetMonitor,I can see the consumer group using offsets.storage as "kafka",and fetch the group offset normally. but I found that the offsetapp.db was alway empty with ddl but without any data.Is it something configured unproperly?Thanks

**Comment by rcasey212** [comment]
@copoo I didn't actually change the code which reads/write to the db, so it should not be affected by this change.  My own personal build writes to the db without any issue.  Until this gets patched, would you try cloning from here instead: https://github.com/Morningstar/kafka-offset-monitor.  This is the fork from which I made the PR.  It isn't 100% in sync with my personal repo, which I will delete.

**Comment by rcasey212** [comment]
@mortimerp9 What is the process to get this merged?  Is there something I need to do?

Also I'll have a new PR for this in a few days that adds some robustness.

**Comment by haggy** [comment]
Why hasn't this been merged?

**Comment by rcasey212** [comment]
I get the impression that Quantifind does not care about this project anymore. :(

**Comment by rcasey212** [comment]
Definitely a bummer that there is 0 movement on this PR.

**Comment by rcasey212** [comment]
Thanks to @Mortimerp9 for approving.

Unfortunately it appears this PR will not get merged.  I provided the agreement which Quantifind requests before submitting the PR, but have never heard anything back from them, via email or otherwise.  

Regardless, I'm back with the promised stability/robustness updates.

You can find the new release here: https://github.com/Morningstar/kafka-offset-monitor/releases/tag/0.4.1
You can also follow me on github here: https://github.com/rcasey212

Here are the release notes:

**v0.4.1 - Stability improvements**
Lots of stability improvements in this release.  Here are the changes:

**Functional changes:**
* Graphs could sometimes be difficult to read because you would see non-whole numbers on the y-axis legend, when facts being drawn are always whole numbers. Set y-axis to draw only whole numbers in the legend to make the graph easier to interpret.
* Respect command-line arg kafkaOffsetForceFromStart, starting consumer offset listener clients from the beginning of the log by implementin a ConsumerRebalanceListener.

**Stability improvements:**
* Created function tryParseOffsetMessage to attempt to parse a kafka offset message retrieved from the internal committed offset topic:
  * Handles messages of other types and questionable correctness.
  * Added 100% unit-test coverage for this new function.
* Add robustness to the log-end-offset getter thread:
  * No longer shutting down the application on error. Instead, closing and destroying the client and re-creating it.
  * Sleeping on error before re-creating client and continuing to process
* Deal with thread-safety issues on shared memory between threads that retrieve data from Kafka.
* Stopped polluting consumer groups in zookeeper by not creating a unique consumer group name for the consumer-offset and log-end-offset listener at each client instantiation.
* Improved createNewAdminClient code, simplifying the error paths and property calling close on error.
* Re-factored some of the error handling paths, simplifying them.
* Closing all kafka clients on error so connections do not leak.

**General improvements:**
* Begin to reduce usage of Zookeeper when using offsetStorage = kafka:
  * Override getTopics() in KafkaOffsetGetter to retrieve topics directly from the Kafka broker
  * Override getClusterVis() in KafkaOffsetGetter to retrieve cluster information directly from the Kafka broker.
* Use constants for all property in createNewKafkaConsumer().
* Fixed some bad grammar in error messages.
* Fixed silly com.twitter.util-core dependency in build.sbt.

**Comment by aatchison** [comment]
Thanks so much for this! I'll let you know if it's working well for me.

**Comment by aatchison** [comment]
Unfortunately I'm still having issues. One of our devs tells me there might be a breaking consumer API change in 0.10.0 which is what we are using.

**Comment by rcasey212** [comment]
Hi @aatchison, you might go [here](https://github.com/Morningstar/kafka-offset-monitor), which is where I am tracking this project since this one is defunct.  We are using kafka-offset-monitor v0.4.1 with Kafka v0.10.0 without issue.

**Comment by aatchison** [comment]
Awesome, thanks so much! I will check it out and let you know sometime here
soonish.

**Comment by rcasey212** [comment]
I think there is no reason to keep this open any longer.  Closing.

**Pull request closed without merging**
